In [1]:
import numpy as np
A = np.mat('72 -68;-68 72')
A

matrix([[ 72, -68],
        [-68,  72]])

In [2]:
a,p = np.linalg.eig(A)  # 特征值
print(a)
p

[140.   4.]


matrix([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]])

In [3]:
namuda = np.diag(a)
namuda

array([[140.,   0.],
       [  0.,   4.]])

In [4]:
p**(-1)*A*p

matrix([[1.40000000e+02, 3.61864453e-15],
        [2.75899846e-15, 4.00000000e+00]])

In [5]:
p*namuda*p**(-1)

matrix([[ 72., -68.],
        [-68.,  72.]])

In [6]:
p.T-p**(-1)

matrix([[-1.11022302e-16,  1.11022302e-16],
        [-1.11022302e-16, -1.11022302e-16]])

In [7]:
# 降维压缩
n = 140*p[:,0]
n = np.asarray(n)
n.flatten()

array([ 98.99494937, -98.99494937])

# 奇异值

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [9]:
img_eg = mpimg.imread('timg.jpg')
print(img_eg.shape)

(600, 400, 3)


In [10]:
img_temp = img_eg.reshape(600,400*3) #将图片变成600*1200的矩阵
U,Sigma,VT = np.linalg.svd(img_temp)  # 奇异值从大到小进行排序
print(U.shape)
print(VT.shape)

(600, 600)
(1200, 1200)


In [11]:
sval_nums = 120
img_r1 = (U[:,0:sval_nums]).dot(np.diag(Sigma[0:sval_nums])).dot(VT[0:sval_nums,:])
img_r1 = img_r2.reshape(600,400,3)

NameError: name 'img_r2' is not defined

In [5]:
sval_nums = 120
img_r2 = (U[:,0:sval_nums]).dot(np.diag(Sigma[0:sval_nums])).dot(VT[0:sval_nums,:])
img_r2 = img_r2.reshape(600,400,3)

In [6]:
fig,ax = plt.subplots(1,3,figsize=(24,32))
ax[0].imshow(img_eg)
ax[0].set(title='')