In [1]:
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import matplotlib.style as style

style.use('fivethirtyeight')
plt.rcParams["figure.figsize"] = (14, 7)
plt.figure(dpi=100)

%matplotlib
x=np.linspace(-4, 4, 100)
pdf=stats.norm.pdf(x)#标准正太分布密度函数
cdf=stats.norm.cdf(x)

plt.plot(x,pdf)
plt.fill_between(x,pdf,alpha=0.15)#alpha为0的时候画出的线或点是完全透明的，为1时是完全不透明的。

plt.plot(x,cdf)

plt.text(x=-1.5, y=.7, s="pdf (normed)", rotation=65, alpha=.75, weight="bold", color="#008fd5")#rotation，旋转角度
plt.text(x=-.4, y=.5, s="cdf", rotation=55, alpha=.75, weight="bold", color="#fc4f30")#weight="bold"，粗体字


ImportError: DLL load failed: 找不到指定的模块。

# 基于数据画出分布，先确定样本模型，并估计真实模型，并作出样本与真实模型之间的对比图


In [16]:
import pandas as pd
data = pd.read_table('样本.txt')
len(data)

NameError: name 'r' is not defined

In [ ]:
mean = data.mean()
mean

In [4]:
std = data.std
std

NameError: name 'data' is not defined

In [5]:
def normfun(x,mu, sigma):
    pdf = np.exp(-((x - mu)**2) / (2* sigma**2)) / (sigma * np.sqrt(2*np.pi))
    return pdf

In [6]:
x = np.arange(60, 150,1)

# x数对应的概率密度
y = normfun(x, mean, std)

# 参数,颜色，线宽
plt.plot(x,y, color='g',linewidth = 3)

#数据，数组，颜色，颜色深浅，组宽，显示频率
plt.hist(data, bins =7, color = 'r',alpha=0.5,rwidth= 0.9, normed=True)

plt.title('distribution')
plt.xlabel(' score')
plt.ylabel('Probability')
plt.show()


NameError: name 'mean' is not defined

In [29]:
import numpy as np
a = np.array([10,15,20,25,30,35,40,20])
print(a)

[10 15 20 25 30 35 40]


In [57]:
a.dot(np.array([0.1,0.1,0.2,0.1,0.3,0.15,0.15]))

29.25

In [66]:
x = np.mat("0;1")
y = np.mat("0 1 2")
b = np.array([[0.1,0.20,0.20],[0.15,0.30,0.05]])

In [67]:
b

array([[0.1 , 0.2 , 0.2 ],
       [0.15, 0.3 , 0.05]])

In [68]:
z = x + y

In [69]:
z

matrix([[0, 1, 2],
        [1, 2, 3]])

In [70]:
d = np.array((np.sin(np.pi*z/2))) * b
d

array([[ 0.0000000e+00,  2.0000000e-01,  2.4492936e-17],
       [ 1.5000000e-01,  3.6739404e-17, -5.0000000e-02]])

In [71]:
d

array([[ 0.0000000e+00,  2.0000000e-01,  2.4492936e-17],
       [ 1.5000000e-01,  3.6739404e-17, -5.0000000e-02]])

In [72]:
d.sum()

0.3000000000000001

In [73]:
from scipy import stats 
import numpy as np
from matplotlib import pyplot as plt

In [74]:
x = np.linspace(0, 60, 100)
print(x)
y = stats.uniform.pdf(x, 10, 30)
print(y)
plt.plot(y)
plt.show()

[ 0.          0.60606061  1.21212121  1.81818182  2.42424242  3.03030303
  3.63636364  4.24242424  4.84848485  5.45454545  6.06060606  6.66666667
  7.27272727  7.87878788  8.48484848  9.09090909  9.6969697  10.3030303
 10.90909091 11.51515152 12.12121212 12.72727273 13.33333333 13.93939394
 14.54545455 15.15151515 15.75757576 16.36363636 16.96969697 17.57575758
 18.18181818 18.78787879 19.39393939 20.         20.60606061 21.21212121
 21.81818182 22.42424242 23.03030303 23.63636364 24.24242424 24.84848485
 25.45454545 26.06060606 26.66666667 27.27272727 27.87878788 28.48484848
 29.09090909 29.6969697  30.3030303  30.90909091 31.51515152 32.12121212
 32.72727273 33.33333333 33.93939394 34.54545455 35.15151515 35.75757576
 36.36363636 36.96969697 37.57575758 38.18181818 38.78787879 39.39393939
 40.         40.60606061 41.21212121 41.81818182 42.42424242 43.03030303
 43.63636364 44.24242424 44.84848485 45.45454545 46.06060606 46.66666667
 47.27272727 47.87878788 48.48484848 49.09090909 49.