In [1]:
import numpy as np
A = np.mat('72 -68;-68 72')
A

matrix([[ 72, -68],
        [-68,  72]])

In [2]:
a,p = np.linalg.eig(A)  # 特征值
print(a)
p

[140.   4.]


matrix([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]])

In [3]:
namuda = np.diag(a)
namuda

array([[140.,   0.],
       [  0.,   4.]])

In [4]:
p**(-1)*A*p

matrix([[1.40000000e+02, 3.61864453e-15],
        [2.75899846e-15, 4.00000000e+00]])

In [5]:
p*namuda*p**(-1)

matrix([[ 72., -68.],
        [-68.,  72.]])

In [6]:
p.T-p**(-1)

matrix([[-1.11022302e-16,  1.11022302e-16],
        [-1.11022302e-16, -1.11022302e-16]])

In [7]:
# 降维压缩
n = 140*p[:,0]
n = np.asarray(n)
n.flatten()

array([ 98.99494937, -98.99494937])