In [26]:
import numpy.matlib
import numpy as np
numpy.matlib.empty((3,4))

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
print(numpy.matlib.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [28]:
print(numpy.matlib.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
# print(numpy.matlib.eye((3,5)))
print(numpy.matlib.eye(n=3,M=4,k=0,dtype=float))

TypeError: 'tuple' object cannot be interpreted as an integer

In [35]:
np.matlib.diag([1,2,3,4,5,6,7])

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [31]:
i = np.matrix([[1,3],[2,4]])
print(i)

[[1 3]
 [2 4]]


In [32]:
np.asarray(i)

array([[1, 3],
       [2, 4]])

In [19]:
np.asmatrix(i)

matrix([[1, 3],
        [2, 4]])

# 矩阵加法

In [22]:
import numpy.matlib
import numpy as np

i = numpy.matlib.empty((3,4))
j = numpy.matlib.empty((3,4))
type(i) # 类型
i.shape # 矩阵的结构
print(i)
i.reshape((4,3))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [39]:
# 点乘
import numpy.matlib
import numpy as np
a1 = np.matrix([[3,4],[1,2]])
a2 = np.matrix([[1,2],[3,4]])
a1*a2
numpy.multiply(a1,a2)

matrix([[3, 8],
        [3, 8]])