# 向量的范数

In [13]:
import numpy as np
x = np.array([1,0,-2])
n0 = np.linalg.norm(x,ord=0)
# np.linalg.norm(求范数):linalg=linear（线性）+algebra（代数），norm则表示范数。

In [14]:
n0

2.0

In [15]:
# 矩阵的范数
#和向量的范数一样，矩阵也有范数，假设矩阵A的大小为m∗n，即m行n列。 1-范数，又名列和范数。顾名思义，即矩阵列向量中绝对值之和的最大值。
import numpy as np
x = np.array([[-1, 1, 0],[-4, 3, 0],[1, 0, 2]])
print(x)
n1 = np.linalg.norm(x,ord = 1)
print('norm_1  ', n1)

[[-1  1  0]
 [-4  3  0]
 [ 1  0  2]]
norm_1   6.0


In [17]:
# 2-范数，又名谱范数，计算方法为ATA矩阵的最大特征值的开平方。

# ||A||2=max(λi)−−−−−−−√
# 其中，λi 是ATA矩阵的特征值。
import numpy as np
x = np.array([[-1, 1, 0],[-4, 3, 0],[1, 0, 2]])
print(x)
xtx = np.matmul(x.T, x)
print ("lambda  ", np.linalg.eigvals(xtx))
n2 = np.linalg.norm(x, ord = 2)
print ('norm_2  ', n2, np.sqrt(27.71086452))

[[-1  1  0]
 [-4  3  0]
 [ 1  0  2]]
lambda   [27.71086452  0.03392256  4.25521292]
norm_2   5.264110990106893 5.264110990471231


In [25]:
import numpy as np
i=np.mat(1 2 3;2 3 -5;4 7 1)
np.linalg.matrix_rank(i)

SyntaxError: invalid syntax (<ipython-input-25-b08fd9825791>, line 2)